export const loadFlags = async () => {
  const FLAGS = {};
  const countryNames = {
    AR: "Argentina",
    AU: "Australia",
    AT: "Austria",
    AZ: "Azerbaijan",
    BH: "Bahrain",
    BD: "Bangladesh",
    BE: "Belgium",
    BR: "Brazil",
    BN: "Brunei",
    CA: "Canada",
    CN: "China",
    CU: "Cuba",
    CY: "Cyprus",
    CZ: "Czech Republic",
    DK: "Denmark",
    EG: "Egypt",
    ET: "Ethiopia",
    FI: "Finland",
    FR: "France",
    DE: "Germany",
    GH: "Ghana",
    GR: "Greece",
    HU: "Hungary",
    IN: "India",
    ID: "Indonesia",
    IR: "Iran",
    IE: "Ireland",
    IT: "Italy",
    JM: "Jamaica",
    JP: "Japan",
    JO: "Jordan",
    KZ: "Kazakhstan",
    KE: "Kenya",
    KR: "South Korea",
    LB: "Lebanon",
    MY: "Malaysia",
    MX: "Mexico",
    MA: "Morocco",
    NP: "Nepal",
    NL: "Netherlands",
    NZ: "New Zealand",
    NG: "Nigeria",
    NO: "Norway",
    PK: "Pakistan",
    PH: "Philippines",
    PL: "Poland",
    PT: "Portugal",
    RU: "Russia",
    SG: "Singapore",
    ZA: "South Africa",
    ES: "Spain",
    LK: "Sri Lanka",
    SE: "Sweden",
    CH: "Switzerland",
    SY: "Syria",
    TW: "Taiwan",
    TZ: "Tanzania",
    TJ: "Tajikistan",
    TH: "Thailand",
    TN: "Tunisia",
    TR: "Turkey",
    UA: "Ukraine",
    UG: "Uganda",
    AE: "United Arab Emirates",
    GB: "United Kingdom",
    US: "United States",
    UY: "Uruguay",
    VE: "Venezuela",
    VN: "Vietnam",
    YE: "Yemen",
    HR: "Croatia",
    EE: "Estonia",
    IS: "Iceland",
    LV: "Latvia",
    LI: "Liechtenstein",
    LT: "Lithuania",
    LU: "Luxembourg",
    MT: "Malta",
    SK: "Slovakia",
    SI: "Slovenia",
    PE: "Peru",
    CO: "Colombia",
    RS: "Serbia",
  };

  const flagFiles = import.meta.glob("../helpers/svg/*.svg");

  for (const path in flagFiles) {
    const isoCode = path.split("/").pop().replace(".svg", "").toUpperCase();
    FLAGS[isoCode] = {
      flag: (await flagFiles[path]()).default,
      name: countryNames[isoCode] || "Unknown Country",
    };
  }

  return FLAGS;
};
