const visaRequirementsData = {
	Argentina: [
		'Fill up a visa application form',
		'4 photographs',
		'Certificate of employment addressed to the embassy',
		'Bank Statement 3 months',
		'Ticket copy/Reservation',
		'Hotel reservation',
		'Invitation Letter (Business)',
		'Exit re-entry (expatriate employees)',
		'Iqama Copy (expatriate employees)',
		'Passport must be valid for 6 months',
		'Original passport and photocopy',
		'Period of getting visa: 15 days',
		'Working Days: Saturday to Wednesday',
	],
	Australia: ['no data available'],
	Austria: [
		'Important Information about Schengen Visa, Click Here',
		'Fill up a visa application form',
		'2 photographs (Without head cover for male; female can wear a head cover but the ears and forehead should be shown.)',
		'Original certificate of employment addressed to the embassy (salary, Position, purpose of visit)',
		'Ticket copy/Reservation',
		'Hotel reservation. The embassy only accepts confirmed bookings (directly from the hotel in Austria by fax) and should send by fax from the hotel to you. Please make sure of your bookings before submitting your applications.',
		'Health/travel insurance (will accept Aramco coverage)',
		'Passport must be signed by the passport holder',
		'Invitation letter (business)',
		'Exit re-entry (expatriate employees)',
		'Photocopy of Iqama',
		'Passport must be valid for 6 months upon leaving the country',
		'Original passport and photocopy',
		'Period of getting Visa: 15 days',
		'Original Bank statement (6 months). (Balance must be more than SR 25,000).',
		'Working Days: Saturday to Wednesday',
		'As per Embassy Regulations, Applicants are required to visit Embassy or Application Centers personally for the collection of their biometric data and to submit the visa application. The biometric data is valid for 5 years and children under the age of 12 are exempt from biometric data collection. An Applicant may submit his visa application along with his family’s application on their behalf. AlFifa will collect back the passports for applicants as requested, passport submission receipt is required.',
		'Note: Please make sure to include a copy of the insurance, ticket and the passport in each of the files of the family members.',
	],
	Azerbaijan: [
		'The period of its validity is established for the single entry-exit visa from three days to three months, and for multiple entry-exit visas up to one year. If the visa is not used within this period it becomes invalid.',
		'A return visa might be given to foreigners who have a personal passport if they apply for it when leaving the Republic of Azerbaijan to return for a period of up to one month. This visa becomes invalid if not used within six months from the date of exit from the Republic of Azerbaijan.',
		'A single or multiple transit visa is granted to foreigners going to other countries but passing through the territory of Republic of Azerbaijan. If the transit visa has no notes or seals about non-stop passage, the bearer has the right to stay in the Republic of Azerbaijan for not longer than five days.',
		'An exit visa is issued to foreigners after they have complied with the appropriate rules on residency in the Republic of Azerbaijan. An exit visa is given without the payment of any state duty.',
		'Foreigners wishing to prolong their visas in order to stay longer in the Republic of Azerbaijan, must do so in advance, before the expiration of the period indicated in their current visa.',
		'The following documents must be submitted to obtain a visa from the Consular Department of the Ministry of Foreign Affairs of the Republic of Azerbaijan:',
		'one copy of the completed visa application form (application forms may be photocopied)',
		'original passport or re-entry permit (no copies accepted)',
		'one passport-size photograph attached to the application form',
		'receipt for the payment of duty',
		'a letter of invitation from the receiving Party',
		'Foreign citizens arriving by aircraft without an entry visa to the Republic of Azerbaijan can obtain a single-entry visa for a short period of time at “Heydar Aliyev” International airport in Baku.',
		'The following documents are required in addition to payment of the duty:',
		'one copy of the completed visa application form (application forms may be photocopied)',
		'one passport-size photograph or a photocopy of the passport data',
	],
	Bahrain: [
		'Fill up a visa application form',
		'2 photographs',
		'Certificate of employment addressed to the embassy',
		'Exit re-entry',
		'Photocopy of Iqama',
	],
	Bangladesh: [
		'Fill up a visa application form',
		'2 Photographs',
		'Certificate of employment addressed to the embassy',
		'Iqama copy/ Saudi ID copy',
		'Exit Re-Entry (Expatriate employees)',
		'Original Passport and Copy',
		'Passport Requirements',
		'PROCEDURE FOR RENEWAL/ ISSUANCE OF PASSPORTS (FOR BANGLADESH NATIONALS WORKING IN KSA)',
		'Bangladesh Embassy remains open Saturday through Wednesday. Office hours are 8.00 am to 4.00 pm. Counters for receiving passport renewal/issuance fees remain open up to 12.30 noon.',
		'INDIVIDUAL APPLICANTS:',
		'Bangladesh Embassy in Riyadh or Bangladesh Consulate in Jeddah has not appointed any agent through which passports can be renewed/issued.',
		'Passport holder himself can tender his passport to the counter of Bangladesh Embassy and get it renewed/issued.',
		'Bangladesh Embassy team regularly visits outlying areas to render consular services including renewal/issuance of Bangladesh passports. Notice of such visits are published in this website, the daily news papers and circulated in the Bangladeshi concentrated companies.',
		'APPLICATION THROUGH COMPANY REPRESENTATIVES:',
		'A company may send passports of their Bangladeshi workers through a designated employee of the company as representative. The representative must produce a letter of authority from the company in their letter pad containing the following:',
		'Name and iqama number of the representative',
		'Passport size photograph of the representative duly attested by an authorized official of the company.',
		'List of passports sent including name of passport holder and passport number.',
		'Clearly specify the mode of services required i, e, urgent or ordinary.',
		'LOST PASSPORTS:',
		'Requirements for the lost passport are the following:',
		'Copy of the old passport and copy of Iqama.',
		'Certificate from Immigration to issue a new passport in lieu of lost one in original.',
		'Original computer print from the Immigration office.',
		'Copy of the advertisement in news paper with its name and date.',
		'Letter from the sponsor to Embassy in original.',
		'8 copies of recent photographs. (6 copies of passport size (40 X 50 mm) and 2 copies of stamp size photographs.)',
		'A prescribed ‘form for new passport’ to be filled up and submitted.',
		'A prescribed ‘form of Notary’ to be filled up and submitted.',
		'Ordinary fee is applicable and to be delivered after 07 days.',
	],
	Belgium: [
		'Important Information about Schengen Visa, Click Here',
		'Fill up a visa application form',
		'2 photographs (without head cover for Male; Female can wear a head cover but the ears and forehead should be shown.)',
		'Certificate of employment addressed to the embassy (salary, position, and purpose of visit)',
		'Bank statement (3 months). (Balance must be more than SR 25,000).',
		'Photocopy of ticket',
		'Hotel reservation should be match with the ticket.',
		'Health/travel insurance',
		'Passport must be signed by the passport holder',
		'Invitation letter (business)',
		'Exit re-entry (expatriate employees)',
		'Photocopy of iqama/saudi id',
		'Original passport and photocopy',
		'Passport must be valid for 6 months upon leaving the country',
		'Period of getting visa: 25 days',
		'Working Days: Saturday to Wednesday',
		'Applicants are required to visit Embassy or Application Centers personally for the collection of their biometric data and to submit the visa application. The biometric data is valid for 5 years and children under the age of 12 are exempt from biometric data collection. An Applicant may submit his visa application along with his family’s application on their behalf. AlFifa will collect back the passports for applicants as requested, passport submission receipt is required.',
	],
	Brazil: [
		'Tourist Visa Requirements',
		'a. Visa Application Form (one per applicant) must be filled in at https://scedv.serpro.gov.br. Fill in the form. Upload requested documents. Click “SEND” to receive your processing number and receipt. Print the receipt. Attach one passport-size photograph but do not staple the photo; glue it, if possible. Sign the receipt. For the photograph it is required front view and white background, professionally printed.',
		'b. Applicant’s passport, valid for no less than 6 months, with at least two blank pages. Please note that pages reserved for amendments cannot be used for visa purposes. Soiled, damaged or defaced passports will not be accepted.',
		'c. Copy of Saudi/Yemeni residence visa.',
		'd. Certificate of good behavior (international model) issued by the country of residence and stamped by the Ministry of Foreign Affairs in Riyadh or Sanaa. The certificate must be issued no more than 90 days prior to delivery at this Embassy.',
		'SPECIFIC REQUIREMENTS PER CATEGORY',
		'1. Technician, contractor, volunteer, specialist, scientist and researcher linked to official entities, private or non-governmental under the shelter of a cooperation agreement recognized by the Brazilian Ministry of External Relations (RN n.º 43/1999)',
		'- Copy of the international agreement, proof of professional expertise and letter from sponsoring organization informing activities to be pursued by the applicant and attesting to the following: that the organization will be responsible for repatriating the applicant (and his/her family, as the case may be) once the visa expires or the agreement ceases to exist, and that the applicant will not receive any payment from a Brazilian-based entity;',
		'2. For trainees in the operation of equipment or machines made in Brazil the validity of the visa will be a maximum of 60 days, which can be renewed in Brazil. Specific requirements are:',
		'- Letter duly notarized by a Notary Public in Brazil from the company with headquarters in Brazil describing the activities to be undertaken by the applicant, its location, duration, and declaring that the trainee will not receive any payment from a Brazilian source.',
		'Business Requirements',
		'a. Visa Application Form (one per applicant) must be filled in at https://scedv.serpro.gov.br. Fill in the form. Click “SEND” to receive your processing number and receipt. Print the receipt. Attach one passport-size photograph but do not staple the photo; glue it, if possible. Sign the receipt. For the photograph it is required front view and white background, professionally printed.',
		'b. Applicant’s passport, valid for no less than 6 months, with at least two blank pages. Please note that pages reserved for amendments cannot be used for visa purposes. Soiled, damaged or defaced passports will not be accepted.',
		'c. Copy of the passport identification pages.',
		'd. If non-Saudi or non-Yemeni, copy of Saudi/Yemeni iqama or residence visa; if Yemeni living in the KSA, or Saudi living in Yemen, iqama or respective residence visa should be provided.',
		'e. Copy of your round-trip booked itinerary (reservation, no need to buy the ticket) showing travel to and from Brazil (informing passenger’s name, itinerary, flight number and arrival/departure dates).',
		'f. Confirmation of hotel reservation (name, address and telephone number) or name and address of intended accommodation.',
		'g. Invitation letter, in Portuguese language with CNPJ nº (Company Registration in Brazil) on the company letter-head.',
		'h. Letter from sponsor bearing responsibility for applicant’s return to Saudi Arabia or Yemen and stating: Applicant’s position, Applicant’s monthly wages, Purpose of trip.',
		'i. If self-employed, trade license from the company and company letter head informing the ownership.',
		'Passport Requirements',
		'Brazilian citizens must follow two steps to apply for a Brazilian passport:',
		'Step 1 – Fill out the online form available at https://scedv.serpro.gov.br and print the Delivery Receipt of Application (RER) generated at the end of the online process.',
		'Step 2 – Bring to the Consular Section of the Embassy in Riyadh the printed RER duly signed and the required documents, listed below. If you cannot come personally to the Embassy in Riyadh, we accept that the RER and the required documents listed below be sent to us by DHL. In this case, the payment of the passport should be done directly to DHL office, which will transfer the money to us. The Embassy shall not be held accounted for the loss of original documents, including the passport issued, during shipment process by DHL.',
		'• A recent photo 3x4cm color, white background, undated;',
		'• Original of previous passport (which will be returned to you);',
		'• Copy of previous passport;',
		'• Original birth certificate, for those not married, or if married, the Brazilian marriage certificate. We can also accept the Brazilian identity card if it contains the record of birth or marriage certificate in it;',
		'• Copy of the Brazilian document presented in the previous item;',
		'• Election Certificate (Certificado de Quitação Eleitoral) for citizens over 18 years old and under 70 years old, issued by the Superior Electoral Court website; and',
		'• For citizen males, between 18 and 45 years old, Military Certificate or equivalent.',
		'If the citizen is under 18 years of age, besides the documents mentioned above, add:',
		'• Authorization for Issuing Passport for a Minor signed by both parents in front of the consular officer. If parents cannot come to the Embassy, the Embassy can legalize the signature by means of similarity only if the parents have already previously filed signature card at the Consular Section.',
		'• In the case of a parent being a non-Brazilian citizen and unable to come personally to the Embassy, this foreign parent’s signature must be notarized at the Embassy of his/her country of origin or by a notary public;',
		'• Original and copy of parents’ passport or Brazilian identity.',
	],
	Brunei: [
		'Fill up a visa application form',
		'3 photographs',
		'Certificate of employment addressed to the embassy',
		'Hotel reservation',
		'Invitation letter (business)',
		'Original passport and copy',
	],
	Canada: [
		'Fill up a visa application form',
		'2 photographs',
		'Certificate of employment addressed to the embassy (salary)',
		'Bank statement (6 months)',
		'Bank draft “the receiver general for Canada“ (for single entry CAD$75; multiple entry CAD$150)',
		'Invitation letter (business)',
		'Exit re-entry (expatriate employees)',
	],
	China_HongKong: {
		family_visit_tourism: [
			'Original passport with validity more than six months and minimum 2 blank visa pages',
			'Photocopy of the first 2 pages (personal information) of the passport and the recent Chinese visa page if there is any',
			'One fully completed visa application form in Chinese or English, attached with two of the applicant’s recent color photographs (30mm X 40 mm)',
			'FOR BUSINESS TRIPS: SCANNED Invitation letter from China',
			'(For Pakistani and Turkish Nationals: Original Invitation Letter sent by courier from China and attested by Ministry of Foreign Affairs inside China)',
			'Company Letter with Salary (For Non-Sabic must be attested by Chamber of Commerce)',
			'Iqama Copy and Exit Re-Entry Copy (For Expatriates)',
			'Saudi I.D Copy and Family Book if traveling with family.',
			'Hotel and Ticket Copy',
			'Passport Copy',
			'Due certificate or document supporting your relationship with the person in China you are to visit (original and photocopy)',
			'Invitation letter',
			'ID card copy or passport copy of the person you are to visit',
			'Copy of Chinese visa page of your inviter’s passport',
			'Return flight tickets and their copies',
			'For tourists purpose, please contact qualified travel agency to join a travel group. And obtain from the said agency the group-visa notice by due Chinese Tourist Bureaus prior to your application. Individual tourist application is not accepted.',
		],
		business: [
			'Letter of Invitation from the company/institution you want to visit in China',
			'Original Visa Notice Sheet from an authorized Chinese governmental apparatus/organization, prescribing the visa validity, number of entries and stay period. The Notice Sheet can be obtained by the above said Chinese company/institution in China',
			'Fully completed Visa Application Form, attached with 2 recent photographs (30 mm X 40mm)',
			'Original passport with validity more than 6 months and minimum 2 blank visa pages',
			'Photocopy of the first 2 pages (personal information pages) of the passport',
			'Saudi Iqama and its copy for non-Saudis',
			'Return flight tickets and hotel reservation in China and their copies',
			'Cover Letter/Letter of Recommendation from your company/institution',
			'Following documents are also required in case of necessity:',
			'Your up-to-date Personal Bank Statement',
			'Photocopy of your company’s Registration Certificate stamped by the Chamber of Commerce and Industry',
			'Non Criminal Clearance Certificate from the Police.',
		],
	},
	Cuba: {
		tourist: [
			'Valid passport and copy of the main page',
			'Filled tourist card form',
		],
		personal: [
			'Personal visa is only given to people with close relatives in Cuba or people married to a Cuban citizen.',
			'Filled personal application form',
			'Valid passport and copy of the main page',
			'Photocopy of marriage certificate',
		],
	},
	Cyprus: [
		'Duly filled application forms',
		'Iqama/Saudi ID Copy',
		'Passport copy along with valid exit re-entry page',
		'Letter from Sponsor attested by Chamber of Commerce',
		'One photograph',
		'Proof for flight reservations and hotel accommodation',
	],
	CzechRepublic: [
		'FILL UP A VISA APPLICATION FORM',
		'2 PHOTOGRAPHS (without head cover for male; female can wear a head cover but the ears and forehead should be shown)',
		'CERTIFICATE OF EMPLOYMENT ADDRESSED TO THE EMBASSY (SALARY, POSITION, PURPOSE OF VISIT)',
		'BANK STATEMENT/PHOTOCOPY OF CREDIT CARD',
		'TICKET COPY/RESERVATION',
		'HEALTH/TRAVEL INSURANCE (Insurance of ARAMCO is not accepted)',
		'HOTEL RESERVATION',
		'PASSPORT MUST BE SIGNED BY THE PASSPORT HOLDER',
		'INVITATION LETTER (BUSINESS)',
		'EXIT RE-ENTRY (EXPATRIATE EMPLOYEES)',
		'PHOTOCOPY OF IQAMA',
		'PASSPORT MUST BE VALID FOR 6 MONTHS UPON LEAVING THE COUNTRY',
		'ORIGINAL PASSPORT AND PHOTOCOPY OF PAGES WITH VISA',
		'As per Embassy Regulations, Applicants are required to visit Embassy or Application Centers personally for the collection of their biometric data and to submit the visa application. The biometric data is valid for 5 years and children under the age of 12 are exempt from biometric data collection. An Applicant may submit his visa application along with his family’s application on their behalf. AlFifa will collect back the passports for applicants as requested, passport submission receipt is required.',
	],
	Denmark: [
		'You must apply for a visa at the embassy representing the country where your main destination is. If your main destination cannot be ascertained, the Schengen State through which you first enter the territory of these countries is responsible for receiving your application.',
		'You can apply for a visa for a short stay of 1 to 90 days valid for all Schengen countries. Process time minimum 12 working days – and can take up to 8 weeks.',
		'Visa section is open Saturday to Tuesday 9am to 2pm',
		'Application forms must be filled in using BLOCK LETTERS.',
		'You must present the following documents:',
		'Saudi Arabian citizens going on a business trip:',
		'1 application form filled in correctly and in detail and signed by the applicant.',
		'2 color photos in size 3.5 by 4.5 cm (not more than 6 months old) with a light background. Photo must be taken up close and the distance between the chin and the top of the head on the photo must account for 70%-80% of the photo. On the photo the applicant must have his/her hair tucked behind the ears. If wearing a veil, the ears, nose, eyes and forehead must be visible. No head cover allowed for men.',
		'Passport (must be valid 3 months beyond the stay in Schengen).',
		'Flight reservation should be handed in with your application.',
		'Invitation from the company in Denmark must be sent/faxed directly to the Embassy.',
		'Travel medical insurance (minimum EURO 30,000) incl. repatriation. Policy wording is required.',
		'3 months bank statement from the date of application',
		'Saudi Arabian citizens going for tourism:',
		'1 application form filled in correctly and in detail and signed by the applicant.',
		'2 color photos in size 3.5 by 4.5 cm (not more than 6 months old) with a light background. Photo must be taken up close and the distance between the chin and the top of the head on the photo must account for 70%-80% of the photo. On the photo the applicant must have his/her hair tucked behind the ears. If wearing a veil, the ears, nose, eyes and forehead must be visible. No head cover allowed for men.',
		'Passport (must be valid 3 months beyond the stay in Schengen).',
		'Flight reservation and hotel booking should be handed in with your application.',
		'Travel medical insurance (minimum EURO 30,000) incl. repatriation. Policy wording is required.',
		'3 months bank statement from the date of application',
		'IN BOTH CASES: If a visa can be issued, you MUST bring a return ticket when you pick up the passport from the Embassy.',
		'Expatriates going on a business trip:',
		'1 application form filled in correctly and in detail and signed by the applicant.',
		'2 color photos in size 3.5 by 4.5 cm (not more than 6 months old) with a light background. Photo must be taken up close and the distance between the chin and the top of the head on the photo must account for 70%-80% of the photo. On the photo the applicant must have his/her hair tucked behind the ears. If wearing a veil, the ears, nose, eyes and forehead must be visible. No head cover allowed for men.',
		'Passport or Travel Document (Passport must be valid 3 months beyond the stay in Schengen. A Travel Document must be valid 6 months beyond the stay in Schengen)',
		'Exit/Re-entry visa to Saudi Arabia must be valid 3 months, and if a Travel Document is used, 6 months beyond the stay in Schengen.',
		'Sponsor letter with details of work contract, purpose of visit and stamped by the Chamber of Commerce.',
		'Copy of Iqama.',
		'Invitation from the company in Denmark must be sent/faxed directly to the Embassy.',
		'Flight reservation.',
		'Travel medical insurance (minimum EURO 30,000) incl. repatriation. Policy wording is required.',
		'3 months bank statement from the date of application',
		'You must present yourself at the Embassy when you hand in the application. If a visa can be issued, a return ticket must be shown when the passport will be picked up at the Embassy.',
		'Expatriates going for tourism:',
		'1 application form filled in correctly and in detail and signed by the applicant.',
		'2 color photos in size 3.5 by 4.5 cm (not more than 6 months old) with a light background. Photo must be taken up close and the distance between the chin and the top of the head on the photo must account for 70%-80% of the photo. On the photo the applicant must have his/her hair tucked behind the ears. If wearing a veil, the ears, nose, eyes and forehead must be visible. No head cover allowed for men.',
		'Passport or Travel Document (Passport must be valid 3 months beyond the stay in Schengen. A Travel Document must be valid 6 months beyond the stay in Schengen).',
		'Exit/Re-entry visa to Saudi Arabia must be valid 3 months beyond the stay in Schengen. If a Travel Document is used, 6 months beyond the stay in Schengen.',
		'Guarantee letter of the sponsor in Saudi Arabia mentioning salary, length of labor contract of the visa applicant and holiday time allowed, stamped by the Chamber of Commerce.',
		'Copy of Iqama.',
		'Hotel booking.',
		'Flight reservation with dates corresponding to those mentioned in the Hotel booking.',
		'Travel medical insurance (minimum EURO 30,000) incl. repatriation. Policy wording is required.',
		'3 months bank statement from the date of application',
		'You must present yourself at the embassy when you hand in the application. If a visa can be issued, a return ticket with dates corresponding to those mentioned in the hotel booking, must be shown when the passport will be picked up at the embassy.',
		'There will be no refund of visa handling fees.',
		'Please note, that additional proofs and documents may be required in some cases.',
		'As per Embassy Regulations, Applicants are required to visit Embassy or Application Centers personally for the collection of their biometric data and to submit the visa application. The biometric data is valid for 5 years and children under the age of 12 are exempt from biometric data collection. An Applicant may submit his visa application along with his family’s application on their behalf. AlFifa will collect back the passports for applicants as requested, passport submission receipt is required.',
	],
	Egypt: [
		'Fill up a visa application form',
		'2 photographs',
		'Certificate of employment addressed to the embassy',
		'Iqama copy',
		'Exit re-entry (expatriate employees)',
		'Original passport and copy',
	],
	Ethiopia: ['No data found'],
	France: [
		'Fill up a visa application form',
		'2 photographs (white background; without head cover for male; female can wear a head cover but the ears and forehead should be shown)',
		'Certificate of employment addressed to the embassy (salary, position, purpose of visit)',
		'Bank statement (3 months). (Balance must be more than SR 25,000)',
		'Photocopy of ticket',
		'Hotel reservation (copy directly from the hotel + hotel voucher). It should match with the ticket',
		'Health/travel insurance',
		'Passport must be signed by the passport holder',
		'Invitation letter (business)',
		'Exit re-entry (expatriate employees)',
		'Photocopy of Iqama (expatriate employees)',
		'Passport must be valid for 6 months upon leaving the country',
		'Original passport and photocopy',
		'Parental Consent Letter if Minor is travelling without their parents/guardian and Passport Copy, Saudi I.D and Family Book of Father',
		'Financial Guarantee Letter from the Father/Guardian supporting the Trip and Credit Card Copy',
		'Booking an appointment in the embassy through this link (France Embassy) and print the receipt',
		'As per Embassy Regulations, applicants are required to visit Embassy or Application Centers personally for the collection of their biometric data and to submit the visa application. The biometric data is valid for 5 years and children under the age of 12 are exempt from biometric data collection. An applicant may submit his visa application along with his family’s application on their behalf. AlFifa will collect back the passports for applicants as requested, passport submission receipt is required.',
	],
	Finland: [
		'Fill up a visa application form',
		'2 photographs (No head cover allowed for men)',
		'Certificate of employment addressed to the embassy',
		'Bank statement (Balance must be more than SR 25,000)',
		'Original ticket',
		'Hotel reservation should match with the ticket',
		'Health/travel insurance (will not accept Aramco coverage)',
		'Passport must be signed by the passport holder',
		'Invitation letter (business)',
		'Exit re-entry (expatriate employees)',
		'Iqama copy',
		'Passport must be valid for 6 months',
		'Original passport and copy',
		'Travelers check for $150 per day (expatriate employees)',
		'Global travel order (business)',
		'Period of getting visa: 3 weeks',
		'The applicant must go in person during the passport submission or at the collection to the Embassy',
		'As per Embassy Regulations, applicants are required to visit Embassy or Application Centers personally for the collection of their biometric data and to submit the visa application. The biometric data is valid for 5 years and children under the age of 12 are exempt from biometric data collection. An applicant may submit his visa application along with his family’s application on their behalf. AlFifa will collect back the passports for applicants as requested, passport submission receipt is required.',
	],
	Germany: [
		'Fill up a visa application form',
		'2 photographs (3.5cm X 4.5cm with WHITE BACKGROUND and without head cover for men)',
		'Certificate of employment addressed to the embassy',
		'Bank statement (3 months). (Balance must be more than SR 25,000)',
		'Ticket reservation',
		'Hotel reservation (copy directly from the hotel) should match with the ticket',
		'Health/travel insurance certificate',
		'Invitation letter (business)',
		'Exit re-entry copy (expatriate employees)',
		'Photocopy of Iqama (expatriate employees)',
		'Saudi I.D. Copy, Family Book Copy if travelling with family',
		'Original passport and photocopy',
		'Tourist / Business Visa, please make an appointment for the submission of documents through this link: https://www.visaservices.in/JVAC-Riyadh-App/AppScheduling/AppScheduling.aspx',
		'Financial Guarantee Letter from the Father/Guardian supporting the trip and Credit Card copy',
		'As per Embassy Regulations, applicants are required to visit Embassy or Application Centers personally for the collection of their biometric data and to submit the visa application. The biometric data is valid for 5 years and children under the age of 12 are exempt from biometric data collection. An applicant may submit his visa application along with his family’s application on their behalf. AlFifa will collect back the passports for applicants as requested, passport submission receipt is required.',
	],
	Ghana: [
		'Fill up a visa application form',
		'4 photographs',
		'Certificate of employment addressed to the embassy',
		'Hotel reservation',
		'Valid international yellow fever vaccination certificate',
		'Iqama copy / Saudi ID copy',
	],
	Greece: [
		'Fill up a visa application form',
		'2 photographs (white background, without head cover for male; female can wear a head cover but the ears and forehead should be shown)',
		'Certificate of employment addressed to the embassy (salary, position, purpose of visit)',
		'Bank statement (3 months). (Balance must be more than SR 25,000)',
		'Original ticket',
		'Hotel reservation should match with the ticket',
		'Health/travel insurance',
		'Passport must be signed by the passport holder',
		'Invitation letter (business)',
		'Exit re-entry (expatriate employees)',
		'Photocopy of Iqama (expatriate employees)',
		'Passport must be valid for 6 months upon leaving the country',
		'Original passport and photocopy',
		'As per Embassy Regulations, applicants are required to visit Embassy or Application Centers personally for the collection of their biometric data and to submit the visa application. The biometric data is valid for 5 years and children under the age of 12 are exempt from biometric data collection. An applicant may submit his visa application along with his family’s application on their behalf. AlFifa will collect back the passports for applicants as requested, passport submission receipt is required.',
	],
	Hungary: [
		'Important Information about Schengen Visa, Click Here',
		'Visa application form to be completed perfectly',
		'2 photographs',
		'Certificate of employment addressed to the embassy (salary, position, purpose of visit)',
		'Original ticket',
		'Hotel reservation direct from the Hotel should be match with the ticket',
		'Health / travel insurance',
		'Passport must be signed by the passport holder',
		'Invitation letter (business)',
		'Exit re-entry (expatriate employees)',
		'Photocopy of Iqama/Saudi id',
		'Passport must be valid for 6 months upon leaving the country',
		'Original passport and photocopy',
		'Bank statement (6 months). (Balance must be more than SR 25,000)',
		'As per Embassy Regulations, Applicants are required to visit Embassy or Application Centers personally for the collection of their biometric data and to submit the visa application. The biometric data is valid for 5 years and children under the age of 12 are exempt from biometric data collection. An Applicant may submit his visa application along with his family’s application on their behalf. AlFifa will collect back the passports for applicants as requested, passport submission receipt is required.',
	],
	India: [
		'Fill up a visa application form',
		'2 photographs',
		'Photocopy of Iqama/Saudi ID',
		'Original Passports',
		'Certificate of employment addressed to the embassy',
		'Hotel Reservation copy',
		'Ticket copy',
	],
	Indonesia: [
		'Fill up a visa application form',
		'2 photographs',
		'Original ticket and photocopy',
		'Exit re-entry (expatriate employees)',
		'Photocopy of Iqama/Saudi id',
		'Note: processing of application will take one week',
		'Passport Renewal Requirements:',
		'2 photographs',
		'Original Passport',
		'Copy of Iqamma',
		'Sponsor ID Copy',
		'Original filled application (available in our office)',
		'Additional Application Form:',
	],
	Ireland: [
		'Fill up a visa application form',
		'3 photographs (white background, without head cover)',
		'Certificate of employment addressed to the embassy (salary)',
		'Ticket copy/reservation',
		'Hotel reservation should be match with the ticket',
		'Invitation letter (business)',
		'Exit re-entry (expatriate employees)',
		'Photocopy of Iqama',
		'Bank statement – English (3 months). (Balance must be more than SR 25,000)',
	],
	Italy: [
		'Important Information about Schengen Visa, Click Here',
		'Fill up a visa application form',
		'2 photographs (3.5cm X 4.5cm White Background and without head cover for men only)',
		'Original certificate of employment addressed to the embassy (salary, Position, purpose of visit)',
		'Ticket copy/Reservation',
		'Hotel reservation should be match with the ticket',
		'Health/travel insurance Certificate',
		'Passport must be signed by the passport holder',
		'Invitation letter (for business)',
		'Exit re-entry (for expatriate Non Saudi)',
		'Photocopy of Iqama (for expatriate Non Saudi)',
		'Photocopy of Saudi id',
		'Saudi family booklet (Saudi families)',
		'Passport must be valid for 6 months upon leaving the country',
		'Original passport and photocopy',
		'Bank statement (3 months). (Balance must be more than SR 25,000). Credit Card Copy',
		'The Italian company must include the paragraph below in the invitation letter those who are applying for a business visa: “si dichiara di essere consapevole delle responsabilit–enali derivanti dall’art. 12 del t.u. 286/1988 in materia di favoreggiamento dell’immigrazione illegale”',
		'Alfifa provides full service for applicants. Working Days: Sunday to Thursday',
		'As per Embassy Regulations, Applicants are required to visit Embassy or Application Centers personally for the collection of their bio-metric data and to submit the visa application. The bio-metric data is valid for 5 years and children under the age of 12 are exempt from bio-metric data collection. An Applicant may submit his visa application along with his family’s application on their behalf. AlFifa will collect back the passports for applicants as requested, passport submission receipt is required.',
	],
	Jamaica: [
		'Employment letter in English',
		'Saudi ID copy',
		'UK or US valid visa copy',
		'Application fill and sign (attached)',
		'2 photos',
		'6-month Latest Bank statement in English (minimum 10,000/SR Balance)',
		'Original Passport',
		'Ticket/Hotel Booking copy',
	],
	Japan: [
		'Fill up a visa application form',
		'2 photographs',
		'Certificate of employment addressed to the embassy',
		'Ticket and hotel reservation',
		'Invitation letter (business)',
		'Guarantee letter',
		'Exit re–entry (expatriate employees)',
		'Photocopy of Iqama',
		'Original passport and photocopy',
		'Period of getting visa: 10 days',
		'Working Days: Saturday to Wednesday',
	],
	Jordan: {
		Renewal: [
			'Original old passport plus a copy',
			'2 Personal photos with white Background',
			'Copy of the Jordanian ID and the Saudi Residence Permit (Iqama)',
			'Copy of Jordanian Family ID',
			'A letter of authorization to ALFIFA on the official letterhead of the sponsoring company for the holder of the passport, certified by the Chamber of Commerce and MOFA. (A sample letter is available at our office)',
		],
		VisaRequirements: [
			'Fill up a visa application form',
			'2 photographs',
			'Certificate of employment addressed to the embassy',
			'Exit re-entry (6 months)',
			'Photocopy of Iqama',
			'Sponsor’s id copy/passport copy (housemaid / house driver)',
		],
	},
	Kenya: [
		'FILL UP A VISA APPLICATION FORM',
		'2 PHOTOGRAPHS',
		'CERTIFICATE OF EMPLOYMENT ADDRSSED TO THE EMBASSY',
		'EXIT RE-ENTRY (EXPATRIATE EMPLOYEES)',
		'IQAMA COPY',
		'ORIGINAL PASSPORT AND COPY',
		'LETTER FROM SCHOOL (DEPENDENT)',
	],
	Khazakhstan: ['No data found'],
	Korea: {
		VisitorVisa: [
			'Completed application form',
			'Recent passport size photograph',
			'Visa Fees (151 SR)',
		],
		AdditionalRequirementForNonSaudiApplicant: [
			'A letter from the sponsor explains (the purpose of visit- duration- Accommodation- trip schedule) attested from Saudi Chamber of Commerce',
			'Round trip Ticket',
			'Exit and Re-entry Visa',
			'Evidence of Financial Support (Bank Statement Minimum 30000 SR)',
			'Hotel Reservation',
			'Iqama photocopy for non Saudi',
		],
		BusinessVisa: [
			'Company’s letter (explain- purpose of visit, duration, accommodation and trip schedule) and attested by Chamber of Commerce',
			'Invitation letter from the host party in Korea addressed to the Korean embassy in the Kingdom of Saudi Arabia explain purpose of visit, duration, accommodation and trip schedule. A Notarization Certificate from authorized lawyer office in Korea should be attached to this invitation + guaranty letter + Certificate for Business Registration',
			'Completed application form',
			'Recent passport size photograph',
			'Visa Fees( SR 151 Single/ SR 345 Multi / SR 230 More than three months)',
			'For Non Saudis',
			'Round trip ticket',
			'Exit and Re-entry Visa',
			'Evidence of Financial Support (Bank Statement 20000)',
			'Hotel Reservation',
			'Iqama copy for non Saudi',
		],
	},
	Lebanon: [
		'Fill up a visa application form',
		'2 photographs',
		'Certificate of employment addressed to the embassy',
		'Photocopy of Iqama',
		'Exit re–entry (6 months)',
		'Sponsor’s id copy/passport copy (house maid/house driver)',
	],
	Malaysia: [
		'FILL UP 3 ORIGINAL VISA APPLICATION FORM',
		'3 PHOTOGRAPHS',
		'CERTIFICATE OF EMPLOYMENT ADDRSSED TO THE EMBASSY (Name, Nationality, Passport No, Salary, Position and Validity of Contract)',
		'TICKET COPY',
		'EXIT RE-ENTRY',
		'ORIGINAL PASSPORT AND COPY',
		'Visa Requirements for Colombian citizens for tourist:',
		'3 Visa application forms (1 typed original + 2 copies) per person, signed by the applicant himself',
		'3 Photos per person',
		'Original + 1 copy of sponsor’s letter mentioning (in English):',
		'A) Name',
		'B) Nationality',
		'C) Passport No',
		'D) Profession',
		'E) Purpose of visit',
		'F) Salary',
		'G) Validity of contract with the company',
		'H) Family details if accompanied (name, Nationality, Passport No, Relationship)',
		'Original + copy of passport (showing all personal details, renewal, date & exit re entry pages). Passport should be valid for minimum six months',
		'Copy of confirm return ticket',
		'Exit re entry visa',
		'Needs to produce US$200.00 per day stay (Original & copy)',
		'Can Enter Malaysia only by Air',
		'Visa Issued for a stay of 14 days only',
	],
	Mexico: [
		'FILL UP A VISA APPLICATION FORM',
		'2 WHITE BACKGROUND PHOTOGRAPHS',
		'CERTIFICATE OF EMPLOYMENT ADDRESSED TO THE EMBASSY',
		'TICKET COPY/ RESERVATION',
		'COPY OF CREDIT CARD',
		'INVITATION LETTER (BUSINESS)',
		'BANK STATEMENT (ENGLISH)',
	],
	Morocco: [
		'FILL UP A VISA APPLICATION FORM AND SIGN IT',
		'ORIGINAL PASSPORT',
		'2 PHOTOGRAPHS',
		'IQAMA COPY',
		'EXIT RE-ENTRY COPY',
		'TICKET COPY',
		'SPONSOR PASSPORT COPY',
		'SPONSOR LETTER (Mention that she is his housemaid and the reason of accompany)',
		'PROOF OF ACCOMODATION (APARTMENT/ HOTEL)',
	],
	Nepal: ['No data found'],
	Netherlands: [
		'Fill up a visa application form',
		'2 photographs (white background; without head cover for Male; Female can wear a head cover but the ears and forehead should be shown.)',
		'Certificate of employment addressed to the embassy (salary, position, Purpose of visit)',
		'Bank statement (3 months). (Balance must be more than SR 25,000).',
		'Original ticket and photocopy',
		'Hotel reservation should be match with the ticket',
		'Health/travel insurance',
		'Passport must be signed by the passport holder',
		'Invitation letter (business)',
		'Photocopy of Iqama',
		'Exit re-entry (expatriate employees)',
		'Passport must be valid for 6 months upon leaving the country',
		'Original passport and photocopy',
		'You need to make appointment Click Here',
	],
	'New Zealand': [
		'Fill up a visa application form',
		'2 photographs (white background; without head cover for male; female can wear a head cover but the ears and forehead should be shown.)',
		'Certificate of employment addressed to the embassy (salary, position, Purpose of visit).',
		'Bank statement (3 months). (Balance must be more than SR 25,000).',
		'Original ticket and photocopy',
		'Hotel reservation should be match with the ticket',
		'Health/travel insurance',
		'Passport must be signed by the passport holder',
		'Invitation letter (business)',
		'Photocopy of iqama',
		'Exit re – entry (expatriate employees)',
		'Passport must be valid for 6 months upon leaving the country',
		'Original passport and photocopy',
	],
	Nigeria: ['No data found'],
	Norway: [
		'Fill up a Visa Application Form.',
		'2 PHOTOGRAPHS (Without head cover for Male; Female can wear a head cover but the ears and forehead should be shown.)',
		'Certificate of Employment addressed to the embassy (SALARY, POSITION, PURPOSE OF VISIT)',
		'Original Ticket',
		'Hotel Reservation should be match with the ticket',
		'Health/Travel Insurance (Insurance of ARAMCO is not accepted)',
		'Passport must be signed by the Passport holder.',
		'Invitation Letter (Business)',
		'Photocopy of Iqama/Saudi ID',
		'EXIT RE-ENTRY (Expatriate Employees)',
		'Passport must be valid for 6 months upon leaving the country.',
		'Original Passport and Photocopy',
	],
	Pakistan: [
		'FILL UP A VISA APPLICATION FORM',
		'2 PHOTOGRAPHS',
		'CERTIFICATE OF EMPLOYMENT ADDRESSED TO THE EMBASSY',
		'ORIGINAL PASSPORT AND COPY',
		'INVITATION LETTER (BUSINESS)',
		'IQAMMA COPY',
	],
	Phillippines: [
		'Passport valid for at least six(6) months beyond the applicants stay in the Philippines',
		'Two (2) photocopies of passport',
		'Duly accomplished visa application form (FA Form No.2) and one (1) Xerox copy of the said form',
		'Two (2) colored photographs (2×2) with plain background',
		'Letter of request from the sponsor/employer, stating the details i.e. rank/position, salary of applicant and purpose of travel to the Philippines',
		'Photocopy of Saudi Exit and Re-entry Visa',
		'Airline computer printouts of the applicant’s flight details also indicating destination after the visa to the Philippines',
		'Original Hotel Booking or Notarized affidavit of the sponsor in the Philippines',
		'Personal appearance upon request of the Consular Officer',
		'If the Purpose of the visit is for RECRUITMENT OF FILIPINO WORKERS, applicant must submit the following:',
		'a. Photocopy of Special Power of Attorney verified by the Office of the Labor Attache',
		'b. Photocopy of Demand Letter stating the number of employees to be hired, their positions, and salaried, etc.',
		'c. Photocopy of approved Block Visa from the Ministry of Foreign Affairs',
		'Note:',
		'Sudanese and Syrian nationals must present a ” LETTER OF NO OBJECTION ” from their respective embassies.',
		'The issuance of visa is subject to the approval of the Visa Officer.',
		'The issuance of visa by the Embassy is NOT A GUARANTEE that the holder will be admitted into the Philippines, Admission of aliens is a function of the Philippine Immigration authorities at the point of entry; hence, they have the FINAL DECISION on whether to admit a foreigner intending to enter the Philippines.',
		'Notice',
		'Nationals from the following countries have to wait five (5) working days before the release of their visas:',
		'Algeria-Azerbaijan- Bangladesh- Egypt- Iran- Iraq- Jordan- Kazakhstan- Kyrgyzstan- Lebanon- Libya- Pakistan-Sudan-Syria-Tajikistan-Turkmenistan-Uzbekistan-Yemen.',
		'Applicants who are holders of TRAVEL DOCUMENTS have to wait approval (CLEARANCE) from Manila before the issuance of their visas.',
	],
	Poland: [
		'Fill up a visa application form onlinehttp://www.e-konsulat.gov.pl/',
		'Appointment Booking from same link above',
		'2 photographs (3.5CM X 4.5CM WHITE BACKGROUND and without head cover for men only.)',
		'Certificate of employment addressed to the embassy',
		'Photocopy of ticket',
		'Hotel reservation should be match with the ticket',
		'Travel / Medical Insurance',
		'Invitation letter (business)',
		'exit re-entry (expatriate employees)',
		'Photocopy of iqama/Saudi id / Family Book if travelling with family',
		'Original passport and photocopy',
		'Bank Statement (Last 3 months)',
	],
	Portugal: [
		'Fill up a visa application form',
		'2 photographs (without head cover for male; female can wear a head cover But the ears and forehead should be shown.)',
		'Certificate of employment addressed to the embassy (salary, position, Purpose of visit)',
		'Original ticket',
		'Hotel reservation',
		'Invitation letter (business)',
		'Health/Travel insurance',
		'Passport must be signed by the passport holder',
		'Exit re-entry (expatriate employees)',
		'Photocopy of iqama/Saudi id',
		'Passport must be valid for 6 months upon leaving the country',
		'Original passport and photocopy',
		'Traveler’s cheque $150 per day (expatriate employees)',
		'Bank statement (6 months)',
		'Photocopy of credit card',
	],
	Romania: [
		'VISA APPLICATION FORM TO BE COMPLETED',
		'2 PHOTOGRAPHS',
		'INTRODUCTION LETTER FROM PERSONNEL ADDRESS TO EMBASSY',
		'TICKET COPY',
		'HOTEL RESERVATION',
		'INVITATION LETTER (BUSINESS)',
		'EXIT RE-ENTRY (EXPATRIATE EMPLOYEES)',
		'IQAMA COPY/ Saudi ID Copy',
		'PASSPORT MUST BE VALID FOR 06 MONTHS',
		'ORIGINAL PASSPORT AND COPY',
		'Travel Insurance',
	],
	Russia: [
		'Fill up a visa application form',
		'2 photographs 3.5*4.5',
		'Certificate of employment addressed to the embassy',
		'Saudi ID',
		'Travel Date',
		'Passport',
	],
	Singapore: [
		'Fill up a visa application form',
		'Copy for the first page of the passport',
		'3 photographs( white background)',
		'Certificate of employment addressed to the embassy',
		'Letter of Introduction (LOI)',
		'Invitation letter (business)',
		'Singapore Approval should be attached with the above requirements.',
	],
	'South Africa': [
		'Visa application form to be completed perfectly',
		'2 Photographs',
		'Introduction Letter from personnel, Address to Embassy',
		'Ticket reservation',
		'Hotel reservation',
		'Health / Travel Insurance ( will accept Aramco coverage )',
		'Invitation Letter ( Business )',
		'Saudi ID copy/Iqama copy',
		'Exit Re-Entry Visa ( Expatriate employees )',
		'Bank Statement Last six months',
		'Letter (if family accompanying)',
		'Period of getting visa : 8 days',
		'Working Days: Saturday to Wednesday',
	],
	Spain: [
		'Important Information about Schengen Visa,Click Here',
		'Fill up a visa application form (2 photocopies)',
		'3 photographs (without head cover for male)',
		'Original certificate of employment addressed to the embassy (salary, position, Purpose of visit)',
		'Bank statement ( 6 months) Original. (Balance must be more than SR 25,000).',
		'Photocopy of ticket',
		'Hotel reservation should be match with the ticket, directly from the hotel by fax.',
		'Health/travel insurance (Original)',
		'Passport must be signed by the passport holder',
		'Exit re-entry (expatriate employees)',
		'Photocopy of iqama',
		'Passport must be valid for 6 months upon leaving the country',
		'Original passport and photocopy',
		'Make appointment with SPAIN EMBASSY before submitting your application in AL FIFA :Book Appointment',
	],
	SriLanka: ['No data found'],
	Sudan: ['No data found'],
	Sweden: {
		'Saudi Arabian citizens going on a business trip': [
			'One Schengen Visa Application form filled in correctly and in details and signed by the applicant.',
			'One Appendix A',
			'Two photos in size 3.5 by 4.5 cm (passport quality, not older than 6 months and without head cover for men).',
			'Passport (must be valid 6 months beyond the stay in Schengen).',
			'Copies of confirmed flight booking.',
			'Invitation from the company in Sweden (stating purpose and duration of the trip, this should be submitted in original or faxed from Sweden).',
			'Travel insurance (Valid in all Schengen countries, covering medical expenses of Euro 30000).',
			'Copies of passport.',
			'Bank Statement, 3 months back if the company is not paying.',
			'Letter from employer stating details of employment incl. salary, purpose and duration of trip (original stamped by Chamber of Commerce).',
		],
		'Saudi Arabian citizens going for tourism, visiting family/friends or other purpose':
			[
				'One Schengen Visa Application form filled in correctly and in details and signed by the applicant.',
				'Two photos in size 3.5 by 4.5 cm (not more than 6 months old).',
				'Passport (must be valid 6 months beyond the stay in Schengen).',
				'Copies of confirmed flight-and hotel booking.',
				'Travel insurance (valid in all Schengen countries, covering medical expenses of Euro 30000)',
				'Bank Statement, 3 months back.',
				'Copies of passport.',
				'Letter from employer stating details of employment incl. salary, purpose and duration of trip (original stamped by Chamber of Commerce).',
				'For visiting family or friends Appendix E, signed and in ORIGINAL, must be submitted with your application. This appendix is obtainable from the Migration Board in Sweden and must be sent from Sweden. It should NOT be sent to the Embassy but turned in with the rest of the application. Also a copy of the Swedish Person Bevis must be provided for the inviting individual.',
			],
		'Expatriates going on a business trip': [
			'One Schengen Visa Application form filled in correctly and signed by the applicant',
			'One Appendix A.',
			'Two photos in size 3.5 by 4.5 cm (not more than 6 months old)',
			'Passport or Travel Documents (Valid 6 months beyond the stay in Schengen)',
			'Exit/Re-entry visa to Saudi Arabia must in case of passport be valid 3 months. And if a Travel Document is used, 6 months beyond the stay in Schengen.',
			'Letter from sponsor approving of trip stating purpose and duration of visit, guaranteeing return (stamped by the Chamber of Commerce if applicable).',
			'Copies of Iqama and passport.',
			'Copies of confirmed flight booking.',
			'Invitation from the company in Sweden (stating purpose and duration of the trip, this should be submitted in original or faxed from Sweden).',
			'Travel insurance (valid in all Schengen countries, covering medical expenses of Euro 30000).',
			'Bank Statement, 3 months back if the company is not paying.',
			'Letter form employer stating details of employment incl. salary, purpose and duration of trip (in original and stamped by the Chamber of Commerce).',
		],
		'Expatriates going for tourism/visit family or friends': [
			'One Schengen Visa Application filled in correctly and signed by the applicant.',
			'Two photos in size 3.5 by 4.5 cm (not more than 6 months beyond old).',
			'Passport or Travel Documents (valid 6 months beyond the stay in Schengen).',
			'Exit/Re-entry visa to Saudi Arabia must in case of Passport be valid 3 months, and if a Travel Document is used, 6 months beyond the stay in Schengen.',
			'Letter from sponsor approving of trip stating purpose and duration of visit, guaranteeing return (stamped by the Chamber of Commerce if applicable).',
			'Copies of Iqama and passport.',
			'Copies of confirmed flight-and hotel booking.',
			'Travel insurance (valid in all Schengen countries, covering medical expenses of Euro 30000)',
			'Bank Statement, 3 months back.',
			'Letter from employer stating details of employment incl. salary, purpose and duration trip (original stamped by Camber of Commerce).',
			'For visiting family or friends Appendix E, signed and in ORIGINAL, must be submitted with your application. This appendix is obtainable form the Migration Board in Sweden and must be sent from Sweden. It should NOT be sent to the Embassy but turned in with the rest of the application. Also a copy of the Swedish Personbevies must be provided for the inviting individual.',
		],
	},
	Switzerland: [
		'Important Information about Schengen Visa,Click Here',
		'Fill up a visa application form',
		'1 photographs without head cover for male (3.5cm X 4.5cm with White Background)',
		'Certificate of employment addressed to the embassy (salary, position, Purpose of visit)',
		'Original bank statement (Last 6 months )',
		'Ticket copy ( Will not accepts reservation)',
		'Hotel Confirmation from Swiss',
		'Medical insurance Certificate( will accept Aramco coverage )',
		'Invitation letter from inviting company in Swiss (Business)',
		'Original passport and photocopy.',
		'Iqama copy /Saudi I.D. Copy, Family Book if travelling with family.',
		'Please call embassy to take appointment. Tel: 01-4881291',
	],
	Syria: [
		'Fill up a visa application form',
		'2 photographs',
		'Certificate of employment addressed to the embassy',
		'Passport must be valid for 6 month upon leaving the country',
		'Original passport and photocopy',
		'For domestic, helper: Sponsor ID/ Passport Copy.',
	],
	Taiwan: [
		'Fill up a visa application form',
		'2 photographs',
		'Certificate of employment addressed to the embassy',
		'Ticket copy/reservation',
		'Hotel reservation',
		'Invitation letter (business)',
		'Exit re – entry (expatriate employees)',
		'Photocopy of iqama',
	],
	Tanzania: [
		'Valid passport with not less than four free pages and not less than six months expiry date ahead.',
		'A letter of introduction from employer or invitation letter from Tanzania sponsor or university / college for student or parent for the applicant below age of majority.',
		'Copy of airline booking or flight details or itinerary.',
		'Two colored passport size photos taken not more than six months back.',
	],
	Tajikistan: [
		'Fill up a visa application form',
		'2 photographs',
		'Certificate of employment',
	],
	Thailand: [
		'Fill up a visa application form',
		'3 photographs',
		'Certificate of employment addressed to the embassy',
		'Ticket reservation',
		'Hotel reservation',
		'Invitation letter (Business)',
		'Photocopy of Iqama',
		'Exit re-entry (expatriate employees)',
		'Passport must be valid for 6 months',
	],
	Tunisia: [
		'Fill up a visa application form(2)',
		'2 photographs',
		'Certificate of employment addressed to the embassy',
		'Original passport and photocopy',
		'Photocopy of Iqama/Saudi id',
		'Need Ticket/Hotel Booking',
		'Non-Saudi need exit/reentry copy/iqama copy.',
	],
	Turkey: [
		'Online Application (Filled by AlFifa)',
		'Appointment (Alfifa staff will take care)',
		'Passport (copy + Original) (Minimum 6 months validity)',
		'Iqama (Original + copy with colour) (Minimum 6 months validity)',
		'Customer’s signature + Employee’s signature Alfifa’s stamp on the iqama',
		'If there is no expiry date on the card please print the expiry date page from the government website.',
		'Write iqama profession in English.',
		'Iqama validity must be printed from the system.',
		'Write (I have seen the original iqama and I took a colour copy)',
		'Exit Re-entry (copy- English) must be checked and printed from government website.',
		'Employment letter (Original -Attested by chamber – English and Arabic) [Should include name, nationality,bank name,account number, salary, join date, iqama no, profession]',
		'Bank statement (Original – stamped – English- last 6 months) and also ATM  card color copy one side,minimum Bank Statement Balance 20,000 SAR.',
		'ALFIFA can do these services as price listed below.',
		'2 new photos (Original 5 cm x 5 cm) Full Face, white background and without a smile. Type the name of the customer behind each photo.',
		'Flight Ticket copy (English)',
		'Hotel booking copy (English)',
		'Travel Medical Insurance.',
		'For Student Only',
		'Original University Acceptance Letter',
		'Original University Paid Receipt',
		'Documents Required from the sponsor (House Helper)',
		'Passport Copy',
		'ID (Copy)',
		'Sponsorship Letter (English) “Draft available at the office”',
		'Bank Statement (Original- Stamped-English – last 6 months ).',
		'Employment letter (Attested by chamber- Original – English)',
		'Ticket (Copy- English) * if he will travel with them',
		'Turkey visa (copy ) * if he will travel with them',
		'Note: Children below 18 years going without mother and father to Turkey need no objection letter notarized. 200/SR extra for this letter to be translated in Turkish language and need more days for processing the visa in this case.',
	],
	UAE: [
		'Fill up a visa application form',
		'2 photographs',
		'Certificate of employment addressed to the embassy (Salary)',
		'Exit re-entry (expatriate employees)',
		'Photocopy of iqama',
	],
	Ukraine: [
		'To enter Ukraine, no visa is required for persons who hold:',
		'- United Nations laissez-passer and are proceeding to Ukraine on business of the UN or of a specialized agency thereof.',
		'- Laissez-passer issued by institutions of the European Union, including the European Commission, and are proceeding to Ukraine on the business of such institutions.',
		'- A diplomatic, service/official/special or ordinary travel passports or any other document that certifies the individual’s identity and confirms his or her citizenship of Armenia, Azerbaijan, Belarus, Kazakhstan, Kyrgyzstan, Moldova, Russia, Tajikistan or Uzbekistan.',
		'- A diplomatic, service/official/special or ordinary travel passports or other document issued for travel abroad for citizens of Georgia, Mongolia, Hungary, Poland and Romania.',
		'- A diplomatic, service/official or special passport of Albania, Argentina, Bosnia and Herzegovina, Brazil, Bulgaria, Chile, China, Croatia, Cuba, Guinea, Iran, Peoples Democratic Republic of Korea, Laos, Lithuania, Slovakia, Turkey, Turkmenistan, Vietnam or Yugoslavia.',
		'- A diplomatic or service passports of Latvia for the period of the holders assignment to the Embassy or consular post of Latvia in Ukraine.',
		'- A diplomatic passports of Estonia, Israel or Mexico.',
		'Who requires a visa:',
		'All persons other than those listed above, who wish to enter Ukraine, are required to have a Ukrainian visa, valid for the period of their intended stay in Ukraine, inserted into their passports or travel documents. Please note that all Ukrainian visas serve as both an entry and exit visa. Holders of ordinary passports of Afghanistan, Angola, Bangladesh, China, Democratic Republic of Congo, Ghana, India, Iraq, Iran, Jordan, Lebanon, Libya, Morocco, Nigeria, Pakistan, Palestine, Syria, Somali, Sri Lanka, Taiwan and Viet Nam, of other countries of the Near and Middle East and Northern Africa are urged to contact the Consular Section prior to submitting their visa applications.',
		'Visa Requirements:',
		'- Fill up a visa application form',
		'- 2 photographs',
		'- Certificate of employment addressed to the embassy',
		'- Original invitation letter',
		'- Photocopy of Iqama/Saudi id',
	],
	Uganda: [
		'FILL UP A VISA APPLICATION FORM',
		'2 PHOTOGRAPHS',
		'CERTIFICATE OF EMPLOYMENT ADDRESSED TO THE EMBASSY',
		'COPY OF ID CARD',
	],
	UK: [
		'Important Note',
		'- On receiving your application, we will send you an sms asking for your availability to fix an appointment with the embassy. Kindly revert back in 2 hours. If there is no response from your end withing the given time ( ie 2 hours), we will proceed to fix the appointment for you.',
		'- On Failure to show up for the appointment, then you can not claim the Visa fee and Service fee from ALFIFA. Please note that all charges are NON-REFUNDABLE.',
		'- If you want to make another appointment, please make the payment again.',
		'- For any doubts, or queries regarding appointment schedule, please contact us through email id: support@alfifavisa.com',
		'- All visa applicants will need to attend the new Visa Application Centre in person to submit their application form, pay their visa fee and have their biometrics taken. There will be female section to serve female applicants operated by female employees.',
		'Online Service: Filling Application and making Appointment (Link)',
		'Latest Update for applicants under 18 years OLD: The validity of 1, 2, 5, and 10 years visit visas for applicants aged under 18 is limited to a date six months after their 18th birthday.',
		'- Example No. 1: a 10 year visa for a 14 year old applicant will only be valid until 6 months after their 18th birthday – i.e. 4 years and 6 months maximum.',
		'Tourist Requirements:',
		'1. Online Application Form',
		'2. Appointment Confirmation',
		'3. 2 Photographs (4.5 x 3.5, White Background)',
		'4. Employment Certificate',
		'5. Financial Sponsorship Letter (if applicable)',
		'6. 6 Months Bank Statement (Original with Stamp from the Bank)',
		'7. Original Passport',
		'8. Saudi ID & Family ID Copy',
		'9. Iqama Copy & Exit Re-Entry Copy (for non-Saudis)',
		'Additional Requirements for Under 18:',
		'1. Letter of consent to get visa from Parents',
		'2. Passport Copies of Parents',
		'3. Visa Copies of Parents',
		'Student Requirements:',
		'1. Online Application Form',
		'2. Appointment Confirmation',
		'3. 2 Photographs (4.5 x 3.5, White Background) with your name written on the reverse side',
		'4. Proof that you can support yourself and pay for your course – this will vary depending on your circumstances',
		'   a. Employment Certificate',
		'   b. Financial Sponsorship Letter (if applicable)',
		'   c. 6 Months Bank Statement (Original with Stamp from the Bank)',
		'5. Original Passport',
		'6. Saudi ID & Family ID Copy',
		'7. Iqama Copy & Exit Re-Entry Copy (for non-Saudis)',
		'8. Acceptance Letter / CAS letter',
		'9. Appendix 8 (must be handwritten by the applicant',
		'10. Proof of parental or other legal guardian consent if you’re under 18. And proof that someone will take care of you when you get to UK if going alone.',
		'11. Health Surcharge',
		'Business Requirements:',
		'1. Online Application Form',
		'2. Appointment Confirmation',
		'3. 2 Photographs (4.5 x 3.5, White Background)',
		'4. Employment Certificate',
		'5. Financial Sponsorship Letter (if applicable)',
		'6. 6 Months Bank Statement (Original with Stamp from the Bank)',
		'7. Invitation Letter (for Business)',
		'8. Original Passport',
		'9. Saudi ID & Family ID Copy',
		'10. Iqama Copy & Exit Re-Entry Copy (for non-Saudis)',
	],
	Uruguay: [
		'FILL UP A VISA APPLICATION FORM',
		'2 PHOTOGRAPHS',
		'CERTIFICATE OF EMPLOYMENT ADDRESSED TO THE EMBASSY',
		'COPY OF SAUDI ID CARD / IQAMA COPY',
		'TICKET RESERVATION',
		'HOTEL RESERVATION',
		'ORIGINAL PASSPORT',
	],
	USA: [
		'US VISA Requirement',
		'- USA Visa Application',
		'- Non Immigrant Application Form (DS 160)',
		'- Passport Renewal',
	],
	Venezuela: [
		'FILL UP A VISA APPLICATION FORM',
		'2 PHOTOGRAPHS',
		'CERTIFICATE OF EMPLOYMENT ADDRESSED TO THE EMBASSY',
		'PASSPORT MUST BE VALID FOR ONE YEAR',
		'ORIGINAL PASSPORT AND COPY',
		'TICKET COPY',
		'BANK STATEMENT FOR 6 MONTHS',
		'HEALTH CERTIFICATE',
		'GLOBAL TRAVEL ORDER (BUSINESS)',
	],
	Vietnam: ['no data found'],
	Yemen: [
		'2 PHOTOGRAPHS',
		'INTRODUCTION LETTER FROM PERSONNEL ADDRESS TO EMBASSY',
		'FILL UP A VISA APPLICATION FORM',
		'HEALTH CERTIFICATE',
		'IQAMA COPY',
	],
};

export default visaRequirementsData;
